project(States C)

# Lib
#add_library(graph-lib graph.c)
#target_include_directories(graph-lib PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})

# Executable
#add_executable(states main.c)
#target_link_libraries(states PRIVATE graph-lib)

# Test
#add_executable(test-graph test-graph.c)
#target_link_libraries(test-graph PRIVATE graph-lib)
#add_test(NAME TestGraph COMMAND test-graph)
